
// Default opacity: 90%
// Light colors are 70% opaque
const COLORS = {
    blue: '#2b8cbe90',
    red: '#de2d2690',
    green: '#2ca25f90',
    yellow: '#f7f43e90',
    lightBlue: '#bdc9e170',
    lightRed: '#fcae9170',
    lightGreen: '#bae4b370',
    lightYellow: '#ffffbf70'
}

const COLOR_SCHEMES = {
    default_blue2red: ['#d7302710', '#f46d4330', '#fdae6140', '#fee09070', '#ffffbf', '#e0f3f8', '#abd9e9', '#74add1', '#4575b4'],
    blue2red: ['#4575b4', '#91bfdb', '#e0f3f8', '#ffffbf', '#fee090', '#fc8d59', '#d73027'],
    green2red: ['#1a9850', '#91cf60', '#d9ef8b', '#ffffbf', '#fee08b', '#fc8d59', '#d73027'],
    categoricals: ['#8dd3c7', '#ffffb3', '#bebada', '#fb8072', '#80b1d3', '#fdb462', '#b3de69', '#fccde5', '#d9d9d9', '#bc80bd', '#ccebc5', '#ffed6f'],
    // Smaller values have more transparent colors
    white2red: ['#ffffb2', '#fed976', '#feb24c', '#fd8d3c', '#fc4e2a', '#e31a1c', '#b10026'],
    white2blue: ['#f1eef6', '#d0d1e6', '#a6bddb', '#74a9cf', '#3690c0', '#0570b0', '#034e7b'],
    white2green: ['#ffffcc', '#d9f0a3', '#addd8e', '#78c679', '#41ab5d', '#238443', '#005a32']
}


export const COLUMNS = {
    hex: 
       ['categorical',
        'numJobs',
        'numCompanies',
        'timeToTokyo',
        'timeAndCostToTokyo',
        'crimeTotalRate',
        'crimeFelonyRobberyRate',
        'crimeFelonyOtherRate',
        'crimeViolentWeaponsRate',
        'crimeViolentAssaultRate',
        'crimeViolentInjuryRate',
        'crimeViolentIntimidationRate',
        'crimeViolentExtortionRate',
        'crimeTheftBurglarySafeRate',
        'crimeTheftBurglarySchoolRate',
        'crimeTheftBurglaryBusinessRate',
        'crimeTheftBurglaryStoreRate',
        'crimeTheftBurglaryEmptyHomeRate',
        'crimeTheftBurglaryHomeSleepingRate',
        'crimeTheftBurglaryHomeUnnoticedRate',
        'crimeTheftBurglaryOtherRate',
        'crimeTheftVehicleRate',
        'crimeTheftMotorcycleRate',
        'crimeTheftBicycleRate',
        'crimeTheftVehicleCargoRate',
        'crimeTheftVendingMachineRate',
        'crimeTheftConstructionRate',
        'crimeTheftPickPocketRate',
        'crimeTheftPurseSnatchingRate',
        'crimeTheftBagLiftingRate',
        'crimeTheftShopliftingRate',
        'crimeTheftOtherRate',
        'crimeOtherIntellectualFraudRate',
        'crimeOtherTakingLostPropertyRate',
        'crimeOtherIntellectualTotalRate',
        'crimeOtherMoralIndecencyRate',
        'crimeOtherOtherRate',
        'greenArea',
        'numHouseholds',
        'noiseMin',
        'noiseMean',
        'noiseMax'],
    chome:
       ['prefCode',
        'cityCode',
        'oazaCode',
        'chomeCode',
        'prefName',
        'districtName',
        'cityName',
        'oazaName',
        'chomeName',
        'perimeter',
        'waterSurface',
        'numHouseholds',
        'greenArea',
        'greenAreaPercent',
        'noiseMin',
        'noiseMean',
        'noiseMax']
};

function strHashCode(str) {
    var hash = 0;
    if (str.length == 0) {
        return hash;
    }
    for (var i = 0; i < str.length; i++) {
        var char = str.charCodeAt(i);
        hash = ((hash<<5)-hash)+char;
        hash = hash & hash; // Convert to 32bit integer
    }
    return hash;
};

// String for categorical values
// Number for numerical values
export const data_format = {
    "categorical": String,
    "chomeCode": Number,
    "chomeName": String,
    "cityCode": Number,
    "cityName": String,
    "crimeFelonyOtherRate": Number,
    "crimeFelonyRobberyRate": Number,
    "crimeOtherIntellectualFraudRate": Number,
    "crimeOtherIntellectualTotalRate": Number,
    "crimeOtherMoralIndecencyRate": Number,
    "crimeOtherOtherRate": Number,
    "crimeOtherTakingLostPropertyRate": Number,
    "crimeTheftBagLiftingRate": Number,
    "crimeTheftBicycleRate": Number,
    "crimeTheftBurglaryBusinessRate": Number,
    "crimeTheftBurglaryEmptyHomeRate": Number,
    "crimeTheftBurglaryHomeSleepingRate": Number,
    "crimeTheftBurglaryHomeUnnoticedRate": Number,
    "crimeTheftBurglaryOtherRate": Number,
    "crimeTheftBurglarySafeRate": Number,
    "crimeTheftBurglarySchoolRate": Number,
    "crimeTheftBurglaryStoreRate": Number,
    "crimeTheftConstructionRate": Number,
    "crimeTheftMotorcycleRate": Number,
    "crimeTheftOtherRate": Number,
    "crimeTheftPickPocketRate": Number,
    "crimeTheftPurseSnatchingRate": Number,
    "crimeTheftShopliftingRate": Number,
    "crimeTheftVehicleCargoRate": Number,
    "crimeTheftVehicleRate": Number,
    "crimeTheftVendingMachineRate": Number,
    "crimeTotalRate": Number,
    "crimeViolentAssaultRate": Number,
    "crimeViolentExtortionRate": Number,
    "crimeViolentInjuryRate": Number,
    "crimeViolentIntimidationRate": Number,
    "crimeViolentWeaponsRate": Number,
    "districtName": String,
    "greenArea": Number,
    "greenAreaPercent": Number,
    "modality": String,
    "noiseMax": Number,
    "noiseMean": Number,
    "noiseMin": Number,
    "numCompanies": Number,
    "numHouseholds": Number,
    "numJobs": Number,
    "oazaCode": Number,
    "oazaName": String,
    "perimeter": Number,
    "pop_0-19yr_A": Number,
    "pop_0-4yr_A": Number,
    "pop_0-4yr_F": Number,
    "pop_0-4yr_M": Number,
    "pop_10-14yr_A": Number,
    "pop_10-14yr_F": Number,
    "pop_10-14yr_M": Number,
    "pop_100yr+_A": Number,
    "pop_100yr+_F": Number,
    "pop_100yr+_M": Number,
    "pop_15-19yr_A": Number,
    "pop_15-19yr_F": Number,
    "pop_15-19yr_M": Number,
    "pop_15-64yr_A": Number,
    "pop_15-64yr_F": Number,
    "pop_15-64yr_M": Number,
    "pop_15yrOrLess_A": Number,
    "pop_15yrOrLess_F": Number,
    "pop_15yrOrLess_M": Number,
    "pop_20-24yr_A": Number,
    "pop_20-24yr_F": Number,
    "pop_20-24yr_M": Number,
    "pop_20-29yr_A": Number,
    "pop_20-29yr_F": Number,
    "pop_20-29yr_M": Number,
    "pop_20-69yr_A": Number,
    "pop_25-29yr_A": Number,
    "pop_25-29yr_F": Number,
    "pop_25-29yr_M": Number,
    "pop_30-34yr_A": Number,
    "pop_30-34yr_F": Number,
    "pop_30-34yr_M": Number,
    "pop_30-44yr_A": Number,
    "pop_30-44yr_F": Number,
    "pop_30-44yr_M": Number,
    "pop_35-39yr_A": Number,
    "pop_35-39yr_F": Number,
    "pop_35-39yr_M": Number,
    "pop_40-44yr_A": Number,
    "pop_40-44yr_F": Number,
    "pop_40-44yr_M": Number,
    "pop_45-49yr_A": Number,
    "pop_45-49yr_F": Number,
    "pop_45-49yr_M": Number,
    "pop_5-9yr_A": Number,
    "pop_5-9yr_F": Number,
    "pop_5-9yr_M": Number,
    "pop_50-54yr_A": Number,
    "pop_50-54yr_F": Number,
    "pop_50-54yr_M": Number,
    "pop_55-59yr_A": Number,
    "pop_55-59yr_F": Number,
    "pop_55-59yr_M": Number,
    "pop_60-64yr_A": Number,
    "pop_60-64yr_F": Number,
    "pop_60-64yr_M": Number,
    "pop_65-69yr_A": Number,
    "pop_65-69yr_F": Number,
    "pop_65-69yr_M": Number,
    "pop_65yr+_A": Number,
    "pop_65yr+_F": Number,
    "pop_65yr+_M": Number,
    "pop_70-74yr_A": Number,
    "pop_70-74yr_F": Number,
    "pop_70-74yr_M": Number,
    "pop_70yr+_A": Number,
    "pop_75-79yr_A": Number,
    "pop_75-79yr_F": Number,
    "pop_75-79yr_M": Number,
    "pop_75yr+_A": Number,
    "pop_75yr+_F": Number,
    "pop_75yr+_M": Number,
    "pop_80-84yr_A": Number,
    "pop_80-84yr_F": Number,
    "pop_80-84yr_M": Number,
    "pop_85-89yr_A": Number,
    "pop_85-89yr_F": Number,
    "pop_85-89yr_M": Number,
    "pop_85yr+_A": Number,
    "pop_85yr+_F": Number,
    "pop_85yr+_M": Number,
    "pop_90-94yr_A": Number,
    "pop_90-94yr_F": Number,
    "pop_90-94yr_M": Number,
    "pop_95-99yr_A": Number,
    "pop_95-99yr_F": Number,
    "pop_95-99yr_M": Number,
    "pop_AgeUnknown_A": Number,
    "pop_AgeUnknown_F": Number,
    "pop_AgeUnknown_M": Number,
    "pop_AverageAge_A": Number,
    "pop_AverageAge_F": Number,
    "pop_AverageAge_M": Number,
    "pop_Foreigner_A": Number,
    "pop_Foreigner_F": Number,
    "pop_Foreigner_M": Number,
    "pop_TotalYears_A": Number,
    "pop_TotalYears_F": Number,
    "pop_TotalYears_M": Number,
    "pop_Total_A": Number,
    "pop_Total_F": Number,
    "pop_Total_M": Number,
    "pop_percent30-44yr": Number,
    "pop_percent70yr+": Number,
    "pop_percentChildren": Number,
    "pop_percentFemale": Number,
    "pop_percentForeigners": Number,
    "pop_percentMale": Number,
    "pop_totalDensity": Number,
    "prefCode": Number,
    "prefName": String,
    "timeAndCostToTokyo": Number,
    "timeToTokyo": Number,
    "waterSurface": Number
};

export const layerConfig = {
    layers: {
        default: {
            colors: COLOR_SCHEMES.default_blue2red,
            reverse: false,
            type: 'standardized',
            interpolate: true
        },
        Hex_NumJobs: {
            colors: ['#ffffe5', '#f7fcb9', '#d9f0a3', '#addd8e', '#78c679'],
            scale: [0, 0.25, 0.5, 0.9, 1.0],
            scaleBy: 'percentage',
            reverse: false,
            type: 'normalized',
            interpolate: true
        },
        Hex_TimeToTokyo: {
            colors: ['#d73027', '#f46d43', '#fdae61', '#fee090', '#ffffbf', '#e0f3f8', '#abd9e9', '#74add1', '#4575b4'],
            // colors: ['#d7191c', '#fdae61', '#ffffbf', '#abd9e9', '#2c7bb6'],
            // colors: chroma.scale(['blue', 'red']).mode('lab').colors(9),
            // scale: [2, 15, 45, 80, 120], // Actual numbers
            reverse: true,
            type: 'standardized',
            interpolate: true
        },
        Hex_CrimeTotalRate: {
            colors: ['#d73027', '#f46d43', '#fdae61', '#fee090', '#ffffbf', '#e0f3f8', '#abd9e9', '#74add1', '#4575b4'],
            scale: [0, 0.0001, 0.0005, 0.001, 0.003, 0.004, 0.005, 0.006, 0.008],
            scaleBy: 'value',
            reverse: true,
            type: 'normalized',
            interpolate: true
        }
    }
};