export const tooltipStyle = {
  position: 'absolute',
  padding: '4px',
  background: 'rgba(0, 0, 0, 0.8)',
  color: '#fff',
  maxWidth: '300px',
  fontSize: '10px',
  zIndex: 9,
  pointerEvents: 'none'
};

export const mapStylePicker = {
  background: '#fff',
  position: 'absolute',
  top: '20px',
  left: '20px',
  zIndex: 100
};

export const layerControl = {
  borderRadius: 3,
  boxShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
  fontFamily:
    'ff-clan-web-pro, "Helvetica Neue", Helvetica, sans-serif !important',
  fontSize: '12px',
  fontWeight: 'bold',
  lineHeight: 1.833,
  width: 200,
  position: 'absolute',
  top: '20px',
  right: '20px',
  padding: '20px',
  zIndex: 100,
  background: 'white',
  height: 200,
  maxHeight: 200,
  overflowX: 'hidden',
  backgroundColor: 'rgba(32, 141, 214, 0.8)'
};

export const charts = {
  background: 'white',
  borderRadius: 3,
  boxShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
  fontFamily:
    'ff-clan-web-pro, "Helvetica Neue", Helvetica, sans-serif !important',
  fontSize: '12px',
  lineHeight: 1.833,
  height: 210,
  padding: '10px',
  position: 'absolute',
  left: 20,
  bottom: 20,
  width: 500,
  zIndex: 100
};

export const spinner = {
  animation: 'linear 2s infinite',
  background: '#1EACC7',
  borderRadius: '50%',
  height: 10,
  width: 10,
  opacity: 0.4,
  position: 'absolute',
  top: 70,
  left: 60,
  transformOrigin: '20px 20px',
  zIndex: 110
};

export const data_format = {
  "chomeCode": Number,
  "chomeName": String,
  "cityCode": Number,
  "cityName": String,
  "crimeFelonyOtherRate": Number,
  "crimeFelonyRobberyRate": Number,
  "crimeOtherIntellectualFraudRate": Number,
  "crimeOtherIntellectualTotalRate": Number,
  "crimeOtherMoralIndecencyRate": Number,
  "crimeOtherOtherRate": Number,
  "crimeOtherTakingLostPropertyRate": Number,
  "crimeTheftBagLiftingRate": Number,
  "crimeTheftBicycleRate": Number,
  "crimeTheftBurglaryBusinessRate": Number,
  "crimeTheftBurglaryEmptyHomeRate": Number,
  "crimeTheftBurglaryHomeSleepingRate": Number,
  "crimeTheftBurglaryHomeUnnoticedRate": Number,
  "crimeTheftBurglaryOtherRate": Number,
  "crimeTheftBurglarySafeRate": Number,
  "crimeTheftBurglarySchoolRate": Number,
  "crimeTheftBurglaryStoreRate": Number,
  "crimeTheftConstructionRate": Number,
  "crimeTheftMotorcycleRate": Number,
  "crimeTheftOtherRate": Number,
  "crimeTheftPickPocketRate": Number,
  "crimeTheftPurseSnatchingRate": Number,
  "crimeTheftShopliftingRate": Number,
  "crimeTheftVehicleCargoRate": Number,
  "crimeTheftVehicleRate": Number,
  "crimeTheftVendingMachineRate": Number,
  "crimeTotalRate": Number,
  "crimeViolentAssaultRate": Number,
  "crimeViolentExtortionRate": Number,
  "crimeViolentInjuryRate": Number,
  "crimeViolentIntimidationRate": Number,
  "crimeViolentWeaponsRate": Number,
  "districtName": String,
  "greenArea": Number,
  "greenAreaPercent": Number,
  "modality": Number,
  "noiseMax": Number,
  "noiseMean": Number,
  "noiseMin": Number,
  "numCompanies": Number,
  "numHouseholds": Number,
  "numJobs": Number,
  "oazaCode": Number,
  "oazaName": String,
  "perimeter": Number,
  "pop_0-19yr_A": Number,
  "pop_0-4yr_A": Number,
  "pop_0-4yr_F": Number,
  "pop_0-4yr_M": Number,
  "pop_10-14yr_A": Number,
  "pop_10-14yr_F": Number,
  "pop_10-14yr_M": Number,
  "pop_100yr+_A": Number,
  "pop_100yr+_F": Number,
  "pop_100yr+_M": Number,
  "pop_15-19yr_A": Number,
  "pop_15-19yr_F": Number,
  "pop_15-19yr_M": Number,
  "pop_15-64yr_A": Number,
  "pop_15-64yr_F": Number,
  "pop_15-64yr_M": Number,
  "pop_15yrOrLess_A": Number,
  "pop_15yrOrLess_F": Number,
  "pop_15yrOrLess_M": Number,
  "pop_20-24yr_A": Number,
  "pop_20-24yr_F": Number,
  "pop_20-24yr_M": Number,
  "pop_20-29yr_A": Number,
  "pop_20-29yr_F": Number,
  "pop_20-29yr_M": Number,
  "pop_20-69yr_A": Number,
  "pop_25-29yr_A": Number,
  "pop_25-29yr_F": Number,
  "pop_25-29yr_M": Number,
  "pop_30-34yr_A": Number,
  "pop_30-34yr_F": Number,
  "pop_30-34yr_M": Number,
  "pop_30-44yr_A": Number,
  "pop_30-44yr_F": Number,
  "pop_30-44yr_M": Number,
  "pop_35-39yr_A": Number,
  "pop_35-39yr_F": Number,
  "pop_35-39yr_M": Number,
  "pop_40-44yr_A": Number,
  "pop_40-44yr_F": Number,
  "pop_40-44yr_M": Number,
  "pop_45-49yr_A": Number,
  "pop_45-49yr_F": Number,
  "pop_45-49yr_M": Number,
  "pop_5-9yr_A": Number,
  "pop_5-9yr_F": Number,
  "pop_5-9yr_M": Number,
  "pop_50-54yr_A": Number,
  "pop_50-54yr_F": Number,
  "pop_50-54yr_M": Number,
  "pop_55-59yr_A": Number,
  "pop_55-59yr_F": Number,
  "pop_55-59yr_M": Number,
  "pop_60-64yr_A": Number,
  "pop_60-64yr_F": Number,
  "pop_60-64yr_M": Number,
  "pop_65-69yr_A": Number,
  "pop_65-69yr_F": Number,
  "pop_65-69yr_M": Number,
  "pop_65yr+_A": Number,
  "pop_65yr+_F": Number,
  "pop_65yr+_M": Number,
  "pop_70-74yr_A": Number,
  "pop_70-74yr_F": Number,
  "pop_70-74yr_M": Number,
  "pop_70yr+_A": Number,
  "pop_75-79yr_A": Number,
  "pop_75-79yr_F": Number,
  "pop_75-79yr_M": Number,
  "pop_75yr+_A": Number,
  "pop_75yr+_F": Number,
  "pop_75yr+_M": Number,
  "pop_80-84yr_A": Number,
  "pop_80-84yr_F": Number,
  "pop_80-84yr_M": Number,
  "pop_85-89yr_A": Number,
  "pop_85-89yr_F": Number,
  "pop_85-89yr_M": Number,
  "pop_85yr+_A": Number,
  "pop_85yr+_F": Number,
  "pop_85yr+_M": Number,
  "pop_90-94yr_A": Number,
  "pop_90-94yr_F": Number,
  "pop_90-94yr_M": Number,
  "pop_95-99yr_A": Number,
  "pop_95-99yr_F": Number,
  "pop_95-99yr_M": Number,
  "pop_AgeUnknown_A": Number,
  "pop_AgeUnknown_F": Number,
  "pop_AgeUnknown_M": Number,
  "pop_AverageAge_A": Number,
  "pop_AverageAge_F": Number,
  "pop_AverageAge_M": Number,
  "pop_Foreigner_A": Number,
  "pop_Foreigner_F": Number,
  "pop_Foreigner_M": Number,
  "pop_TotalYears_A": Number,
  "pop_TotalYears_F": Number,
  "pop_TotalYears_M": Number,
  "pop_Total_A": Number,
  "pop_Total_F": Number,
  "pop_Total_M": Number,
  "pop_percent30-44yr": Number,
  "pop_percent70yr+": Number,
  "pop_percentChildren": Number,
  "pop_percentFemale": Number,
  "pop_percentForeigners": Number,
  "pop_percentMale": Number,
  "pop_totalDensity": Number,
  "prefCode": Number,
  "prefName": String,
  "timeAndCostToTokyo": Number,
  "timeToTokyo": Number,
  "waterSurface": Number
};